# Generated by Django 6.0.6 on 2026-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='secondname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')], default=100),
            preserve_default=False,
        ),
    ]
