# Generated by Django 6.0.6 on 2026-07-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_secondname_student_lastname_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
