# Generated by Django 6.0.6 on 2026-07-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
