# Generated by Django 6.0.6 on 2026-07-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['firstname', 'lastname']},
        ),
    ]
